In [2]:
import pandas as pd
import os, sys
import glob
import numpy as np

In [3]:
path = "csse_covid_19_data/csse_covid_19_daily_reports"
all_files = glob.glob(path + "/*.csv")
li = []
for filename in all_files:
    df = pd.read_csv(filename, encoding="ISO-8859-1")
    li.append(df)
    frame = pd.concat(li, axis=0, ignore_index=True, sort=False)

In [4]:
frame.count()

Province/State     4358
Country/Region     7617
Last Update        7617
Confirmed         56785
Deaths            56363
Recovered         56416
FIPS              44680
Admin2            45054
Province_State    46424
Country_Region    49187
Last_Update       49187
Lat               48901
Long_             48901
Active            49187
Combined_Key      49187
Latitude           4799
Longitude          4799
dtype: int64

In [5]:
df = frame
df = df.fillna('')
df['Province_State'] = df['Province/State'].astype(str) + df['Province_State'].astype(str)
df['Country_Region'] = df['Country/Region'].astype(str) + df['Country_Region'].astype(str)
df['Last_Update'] = df['Last Update'].astype(str) + df['Last_Update'].astype(str)
df['Latitude'] = df['Latitude'].astype(str) + df['Lat'].astype(str)
df['Longitude'] = df['Longitude'].astype(str) + df['Long_'].astype(str)
df = df.drop(columns=['Province/State','Country/Region','Last Update','Lat','Long_','Combined_Key'])
df['Last_Update'] = df['Last_Update'].str[0:10]
df = df.sort_values(by=['Country_Region','Last_Update'])
df.drop_duplicates(keep='first', inplace=True)
df = df[['Province_State','Country_Region','Confirmed','Deaths','Recovered','Active','Latitude','Longitude','FIPS','Admin2']]
df

,Province_State,Country_Region,Confirmed,Deaths,Recovered,Active,Latitude,Longitude,FIPS,Admin2
54255,,Azerbaijan,1,0,0,,,,,
73,,Afghanistan,1,0,0,,,,,
13109,,Afghanistan,1,0,0,,33.0,65.0,,
56409,,Afghanistan,4,0,0,,33.0,65.0,,
12518,,Afghanistan,5,0,0,,33.0,65.0,,
...,...,...,...,...,...,...,...,...,...,...
23800,,Zimbabwe,9,1,0,8,-19.015438,29.154857,,
54175,,Zimbabwe,10,1,0,9,-19.015438,29.154857,,
21005,,Zimbabwe,3,0,0,3,-19.015438,29.154857,,
12467,,occupied Palestinian territory,25,0,0,,31.9522,35.2332,,
12809,,occupied Palestinian territory,0,0,0,,31.9522,35.2332,,

In [16]:
new_df = df.set_index("Country_Region")
new_df = new_df.loc[:,["Death"]]
new_df=pd.DataFrame(new_df)
new_df.head()

KeyError: "None of [Index(['Death'], dtype='object')] are in the [columns]"

In [4]:
df.to_csv("clean_data.csv")